image: node:16

pipelines:
  branches:
    master:
      - step:
          name: Build the site
          caches:
            - node
          script:
            - npm install --legacy-peer-deps
            - npm run fetch
            - git commit -a -m "[skip ci] updating changelog with latest figma changes"
            - git push
            - npm run build
          artifacts:
            - dist/**
      - step:
          name: Deploy to production
          deployment: production
          caches:
            - node
          script:
            - npm run deploy:prod
