// @ts-check

/** @type {import('convertiv-motiv/client-config').Config} */
const config = {
    title: "Handoff Demo Design System",
    homepage: "",
    client: "Convertiv",
    primary: false,
    secondary: false,
    components: true,
    type_sort: [
      "Heading 1",
      "Heading 2",
      "Heading 3",
      "Heading 4",
      "Heading 5",
      "Heading 6",
      "Paragraph",
      "Subheading",
      "Blockquote",
      "Input Labels",
      "Link",
    ],
    design: { color: [], typography: [] },
    assets: { icons: [], logos: [] },
    show_components: true,
    color_sort: ["primary", "secondary", "extra", "system"],
    component_sort: ["primary", "secondary", "transparent"],
    image_styles_help: "Common image dimesions and formats for DEMO",
    image_styles: [
      {
        name: "One Third",
        style: "one_third",
        type: "Content",
        description: "Blog entry input",
        width: 400,
        height: 225,
      },
      {
        name: "Large Banner",
        style: "banner_large",
        type: "Content",
        description: "A wide tall banner image",
        width: 3840,
        height: 634,
      },
      {
        name: "Small Banner",
        style: "banner_small",
        type: "Content",
        description: "A wide shorter banner image",
        width: 3840,
        height: 211,
      },
      {
        name: "PDF Thumbnail",
        style: "ccs_pdf_thumbnail",
        type: "Content",
        description: "PDF thumbnail for resource case studies",
        width: 157,
        height: 141,
      },
      {
        name: "Home Page Promo",
        style: "home_promo",
        type: "Content",
        description: "Square image for the home page",
        width: 200,
        height: 200,
      },
      {
        name: "Home Page Promo",
        style: "home_promo",
        type: "Content",
        description: "Square image for the home page",
        width: 200,
        height: 200,
      },
      {
        name: "Home Page Slider",
        style: "home_page_slider",
        type: "Content",
        description: "An image used on the slider of the home page",
        width: 3840,
        height: 634,
      },
      {
        name: "Microsite page section",
        style: "ms_page_section",
        type: "Content",
        description: "Scaling for the page section on the microsite",
        width: 440,
        height: 260,
      },
    ],
  };
  
  module.exports = config;